# Site settings
title: In Love With Simplicity
email: aash.discover@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Engineer by profession. I like to learn, read and write. This is a place where I write useful, interesting things that I encounter in my professional and personal life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.aashd.me" # the base hostname & protocol for your site
github_username:  geeky-sh
avatar: /images/profile-pic-old.jpg

# Build settings
markdown: kramdown


redcarpet:
  extensions: ['autolink']

plugins:
  - jekyll-spaceship