# Site settings
title: In Love With Simplicity
email: aash.discover@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Engineer by profession. This is a place where I try to write useful, interesting or things to remember
  that I encounter in my professional life. I like to read litrary books and write about my observations and experiences.
  So, there are a few posts where I would have written on topics as well
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.aashd.me" # the base hostname & protocol for your site
github_username:  geeky-sh
avatar: /images/profile-pic-old.jpg

# Build settings
markdown: kramdown


redcarpet:
  extensions: ['autolink']

plugins:
  - jekyll-spaceship